spring:
  datasource:
    url: jdbc:h2:mem://sysw_core:MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2